Update Wesley.yml

diff --git a/.github/workflows/Wesley.yml b/.github/workflows/Wesley.yml
--- a/.github/workflows/Wesley.yml
+++ b/.github/workflows/Wesley.yml
@@ -37,4 +37,13 @@ steps:
       snyk monitor
 # For a list of additional available flags/options see: https://docs.snyk.io/snyk-cli/commands
 
-
+  - name: Snyk Code # Remove || true to fail if there are vulnerabilities
+    run: |
+      snyk code test || true
+  - name: Snyk Container # Rename your image, for testing and failing please add snyk container test before snyk container monitor
+    run: |
+      docker build . -t yourimage:tag
+      snyk container monitor yourimage:tag --file=Dockerfile
+  - name: Snyk IaC # Remove || true to fail if there are vulnerabilities
+    run: |
+      snyk iac test || true
